# Generated by Django 4.0.4 on 2022-05-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='createPassword',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
